
# configs/model/twitter_roberta.yaml

_target_: training.trainers.hf_trainer.HuggingFaceTrainer

name: twitter_roberta

pretrained_name: cardiffnlp/twitter-roberta-base-sentiment

tokenizer_name: cardiffnlp/twitter-roberta-base-sentiment

num_labels: 3

max_length: 512

artifact_dir: artifacts/models/twitter

labels:
  0: negative
  1: neutral
  2: positive

