# configs/dataset/twitter.yaml


name: twitter

raw_path: Data/raw/sent/training.1600000.processed.noemoticon.csv

processed_train_path: Data/processed/twitter/train.csv
processed_val_path: Data/processed/twitter/val.csv
processed_test_path: Data/processed/twitter/test.csv

text_column: text
label_column: sentiment

encoding: latin-1

num_labels: 2