artifact_location: /home/mohamed/sentiment_analyzer/mlruns_test/0
creation_time: 1781271789475
effective_trace_archival_retention: null
experiment_id: '0'
last_update_time: 1781271789475
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
